### ISSUE TITLE
An exception has occurred

### ISSUE THREAD

**Issue by cngege** [SamuelTulach/LightHook#12]
## The code is not complicated, you can reproduce the problem

code
```cpp
int add(int a, int b) {
	return a + b;
}

HookInformation info;
int hookadd2(int a, int b) {
	using fn = int(__fastcall*)(int, int);
	return ((fn)info.Trampoline)(a, b) * 10;
	return 10;
}

int main()
{

	info = CreateHook((void*)&add, (void*)&hookadd2);
	if(!EnableHook(&info)) {
		return 0;
	}
	std::cout << "add(5,6):" << add(5, 6) << std::endl;
	DisableHook(&info);

	return 0;
}
```

in x64Debug

![QQ_1729886163472](https://github.com/user-attachments/assets/d5f0fe16-6960-476d-a9fd-ac2cdb66ba26)

**Comment by SamuelTulach** [comment]
Same as #11 in debug build.

**Comment by cngege** [comment]
> Same as #11 in debug build.

That is to say, there cannot be relative offset instructions in the first 13 bytes of the target function, right?
