### ISSUE TITLE
[BUG] Rename CopyMemory to LHCopyMemory [Windows SDK Conflict]

### ISSUE THREAD

**Issue by CycloneRing** [SamuelTulach/LightHook#4]
Hey, When using LightHook on MSVC and WindowsSDK source cannot be compiled because your implementation of CopyMemory conflicts with Windows SDK  CopyMemory, This can simply be fixed by renaming it to something else like LHCopyMemory.

Regards

**Comment by SamuelTulach** [comment]
[That was fixed already](https://github.com/SamuelTulach/LightHook/pull/5) so I am going to close this.
