### ISSUE TITLE
GetInstructionSize returns wrong value for four byte sub rsp

### ISSUE THREAD

**Issue by ProN00b** [SamuelTulach/LightHook#7]
GetInstructionSize returns wrong value for
48 81 ec d0 00 00 00    sub    rsp,0xd0 
returns 11, should return 7.

**Comment by VXACDev** [comment]
else if ((HOOK_R < 4 && (HOOK_C == 5 || HOOK_C == 0xD)) || (HOOK_R == 0xB && HOOK_C >= 8) || (*b == 0xF7 && !(*(b + 1) & 48)) || FindByte(OP1_IMM32, sizeof(OP1_IMM32), *b))
"& 48" ?? I think this should be & 0x48

**Comment by SamuelTulach** [comment]
The handling was indeed incorrect. I've added more checks and added a test program. It *should* now correctly handle instructions with REX.W bit set. Please let me know if you find any more problems.

![image](https://github.com/user-attachments/assets/5f1a8af2-9ea7-4bcf-ac8f-bce4b245723a)

^ old version would fail at 30+ instances
