### ISSUE TITLE
Will not work on functions with jmp/cmp/nearcall/ any relative offset in the first 14 bytes

### ISSUE THREAD

**Issue by po0p** [SamuelTulach/LightHook#9]
Hey, while overall a great and simple library, it seem to break if a target function has a nearcall (`E8 ? ? ? ?`) in the first 14 bytes. 
Possibly also will break on `jmp` and `cmp` if relative displacement is used.
Reason being this: https://github.com/SamuelTulach/LightHook/blob/fcdba7570fa564ae23c2a66cdf71b9d9334d579c/Source/LightHook.h#L186 
But, considering not having to bring a fullass disassembler to use LH, not an issue per se, just letting you know ;)
Thanks for a great project!

**Comment by SamuelTulach** [comment]
Yeah it's not really fixable. I have modified the `README` to state that more clearly.
